services:
  - type: web
    name: medscreen-backend
    env: go
    rootDir: backend
    buildCommand: go build -o server ./cmd/server/main.go
    startCommand: SERVER_PORT=$PORT ./server
    envVars:
      - key: GO_VERSION
        value: 1.25.0
